---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wconsole-server
  namespace: wconsole
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: wconsole-server
  template:
    metadata:
      labels:
        app: wconsole-server
        build-no: "jenkins-build-no-${ trigger['buildNumber'] }"
    spec:
      containers:
        - name: wconsole-server
          image: 072548720675.dkr.ecr.ap-northeast-2.amazonaws.com/cloudone/webconsole/server
          ports:
            - containerPort: 3000
          env:
          - name: HELLO
            value: WORLD
