# review for PRs
name: SpaceONE Review

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts


    - name: Lint
      run: |
        npm run lint


    - name: Test
      run: |
        npm run test


    - name: Build
      run: |
        npm run build
